name: iris-classification-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas==2.2.0
      - numpy==1.26.3
      - scikit-learn==1.4.0
      - mlflow==2.19.0
      - matplotlib==3.8.2
      - seaborn==0.13.1